server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbauth?createDatabaseIfNotExist=true
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: authentication

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true


info:
  application:
    name: authentication
    version: '@project.version@'

application:
  security:
    jwt:
      secret-key: